# Generated by Django 5.2.15 on 2026-06-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='community_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='community_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
