# Generated by Django 5.2.15 on 2026-07-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_category_community_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='accent_color',
            field=models.CharField(blank=True, default='#FC6104', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_theme',
            field=models.CharField(blank=True, default='default', max_length=40),
        ),
    ]
