# Generated by Django 5.2.15 on 2026-08-01 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_course_banner_image_course_banner_image_alt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('live_class', 'Live class'), ('q_and_a', 'Q&A session'), ('workshop', 'Workshop'), ('launch', 'Cohort launch'), ('deadline', 'Deadline'), ('other', 'Other')], default='live_class', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('join_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_at',),
                'indexes': [models.Index(fields=['starts_at'], name='schedule_ev_starts__070cd5_idx'), models.Index(fields=['course', 'starts_at'], name='schedule_ev_course__39d679_idx')],
            },
        ),
    ]
