# Generated by Django 5.2.15 on 2026-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastnotification',
            name='audience',
            field=models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('admins', 'Admins'), ('all', 'All')], max_length=20),
        ),
    ]
