# Generated by Django 5.2.15 on 2026-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_broadcastnotification_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
