# Generated by Django 5.2.15 on 2026-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_broadcastnotification_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastnotification',
            name='audience',
            field=models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('admins', 'Admins'), ('moderators', 'Moderators'), ('all', 'All')], max_length=20),
        ),
    ]
