# Generated by Django 5.2.17 on 2026-09-16 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def keep_existing_notes(apps, schema_editor):
    """Carry each ticket's `admin_notes` into the thread before the column goes.

    They become ordinary replies, not internal notes: the old code emailed them
    to the person who raised the ticket and printed them on their page, so
    marking them internal now would hide something already sent.
    """
    SupportTicket = apps.get_model("notifications", "SupportTicket")
    SupportTicketMessage = apps.get_model("notifications", "SupportTicketMessage")
    SupportTicketMessage.objects.bulk_create(
        [
            SupportTicketMessage(
                ticket=ticket,
                body=ticket.admin_notes,
                is_internal=False,
                # created_at is auto_now_add, so these carry today's date rather
                # than the date the note was written — the text is what matters.
                author_name="Support",
            )
            for ticket in SupportTicket.objects.exclude(admin_notes="")
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_broadcastnotification_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.supportticket')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RunPython(keep_existing_notes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='supportticket',
            name='admin_notes',
        ),
    ]
