# Generated by Django 5.2.17 on 2026-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_support_ticket_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
