# Generated by Django 5.2.17 on 2026-09-21 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_broadcast_recipient_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='audience_track',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='audience',
            field=models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('admins', 'Admins'), ('moderators', 'Moderators'), ('waitlist', 'Founding members'), ('all', 'All')], max_length=20),
        ),
        migrations.CreateModel(
            name='BroadcastEmailReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered', models.BooleanField(default=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='notifications.broadcastnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('broadcast', 'user')},
            },
        ),
    ]
