# Generated by Django 5.2.15 on 2026-07-31 21:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studentprofile_daily_goal_minutes'),
        ('progress', '0002_lessonprogress_last_position_seconds_lessonnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['student', '-date'], name='progress_da_student_4f0e22_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
