# Generated by Django 5.2.15 on 2026-08-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_dailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
