# Generated by Django 5.2.15 on 2026-08-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_dailyactivity_seconds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonNote',
        ),
    ]
