# Generated by Django 5.2.17 on 2026-09-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='access_source',
            field=models.CharField(choices=[('free', 'Free'), ('payment', 'Payment'), ('admin_grant', 'Admin grant'), ('campaign', 'Campaign')], max_length=20),
        ),
    ]
