# Generated by Django 5.2.15 on 2026-06-12 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MooreSkillUp', max_length=120)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, default='We are performing scheduled maintenance. Please check back soon.', max_length=255)),
                ('student_registration_open', models.BooleanField(default=True)),
                ('audit_retention_days', models.PositiveIntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(max_length=60)),
                ('resource_type', models.CharField(blank=True, max_length=60)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='platform_au_created_a4c737_idx'), models.Index(fields=['action'], name='platform_au_action_286d5a_idx'), models.Index(fields=['actor_email'], name='platform_au_actor_e_d70144_idx'), models.Index(fields=['resource_type'], name='platform_au_resourc_c0ef55_idx')],
            },
        ),
    ]
