# Generated by Django 5.2.15 on 2026-06-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='allow_moderator_announcements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='allow_teacher_announcements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='require_admin_second_approval',
            field=models.BooleanField(default=False),
        ),
    ]
