# Generated by Django 5.2.15 on 2026-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_platformsettings_allow_moderator_announcements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='feature_achievements_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='feature_certificates_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='feature_leaderboard_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='feature_quiz_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='feature_recommendations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='feature_reviews_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
