# Generated by Django 5.2.15 on 2026-06-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_platformsettings_feature_achievements_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='refund_max_progress_percent',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='refund_window_days',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
