# Generated by Django 5.2.15 on 2026-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0004_platformsettings_refund_max_progress_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_student_devices', models.PositiveIntegerField(default=2)),
                ('max_teacher_devices', models.PositiveIntegerField(default=3)),
                ('max_admin_devices', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Authentication settings',
            },
        ),
    ]
