# Generated by Django 5.2.15 on 2026-07-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_authenticationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_course_banner_accent',
            field=models.CharField(default='#FC6104', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_course_banner_text_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_course_banner_theme',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
