# Generated by Django 5.2.17 on 2026-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0007_raise_student_device_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='require_admin_two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='support_response_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
