# Generated by Django 5.2.17 on 2026-09-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0008_admin_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='countdown_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='launch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='launch_cta_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='launch_cta_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='launch_headline',
            field=models.CharField(default='Something is coming', max_length=120),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='launch_message',
            field=models.CharField(blank=True, default='MooreSkillUp opens soon. Practical, job-ready skills taught by people who do the work.', max_length=400),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='launch_state',
            field=models.CharField(choices=[('pre_launch', 'Pre-launch'), ('live', 'Live')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='sign_in_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
