# Generated by Django 5.2.17 on 2026-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_platformsettings_countdown_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='community_label',
            field=models.CharField(blank=True, default='Join the WhatsApp community', max_length=80),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='community_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='launch_state',
            field=models.CharField(choices=[('pre_launch', 'Pre-launch'), ('founding_beta', 'Founding beta'), ('live', 'Live')], default='live', max_length=20),
        ),
    ]
