# Generated by Django 5.2.17 on 2026-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_platformsettings_community_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='referral_early_access_at',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_free_course_at',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_rewards_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
