# Generated by Django 5.2.17 on 2026-09-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0011_platformsettings_referral_early_access_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='privacy_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='terms_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='terms_version',
            field=models.CharField(default='2026-09', max_length=40),
        ),
    ]
