# Generated by Django 5.2.17 on 2026-09-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0012_platformsettings_privacy_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='privacy_url',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='terms_url',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='terms_version',
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('refund', 'Refund Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
