# Generated by Django 5.2.17 on 2026-09-27 15:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_ambassador_studentprofile_ambassador'),
        ('courses', '0014_optional_section_and_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEarningTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('creator', 'Course creator'), ('instructor', 'Course instructor')], default='creator', max_length=20)),
                ('share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_number', models.PositiveSmallIntegerField(default=1)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_reason', models.CharField(blank=True, max_length=255)),
                ('agreement_version', models.CharField(blank=True, max_length=40)),
                ('needs_review', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning_term', to='courses.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_terms', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='TeacherTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_type', models.CharField(choices=[('founding', 'Founding teacher'), ('standard', 'Standard teacher'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('premium_share_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('premium_course_count', models.PositiveSmallIntegerField(default=0)),
                ('standard_share_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('earning_months', models.PositiveSmallIntegerField(default=12)),
                ('creation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('agreement_version', models.CharField(blank=True, max_length=40)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name_plural': 'teacher terms',
            },
        ),
    ]
