# Generated by Django 5.2.17 on 2026-09-27 21:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('category', models.CharField(choices=[('hosting', 'Hosting and servers'), ('database', 'Database'), ('storage', 'Storage'), ('video', 'Video'), ('email', 'Email'), ('domain', 'Domain and DNS'), ('tools', 'Tools and subscriptions'), ('ad_spend', 'Advertising'), ('equipment', 'Equipment'), ('transport', 'Transport'), ('data', 'Data and airtime'), ('other', 'Other')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='organization.department')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'cost entries',
                'ordering': ('-month', 'department__order', 'category'),
            },
        ),
        migrations.CreateModel(
            name='SplitPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operations_percent', models.DecimalField(decimal_places=2, default=Decimal('55.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('founding_teacher_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('standard_teacher_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('target_reserve_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('effective_from', models.DateField(unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'split policies',
                'ordering': ('-effective_from',),
            },
        ),
        migrations.CreateModel(
            name='RevenuePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('processor_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('teacher_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('operations_pool', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserve_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sale_count', models.PositiveIntegerField(default=0)),
                ('sales_missing_fee', models.PositiveIntegerField(default=0)),
                ('operations_percent_used', models.DecimalField(decimal_places=2, default=Decimal('55.00'), max_digits=5)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='finance.splitpolicy')),
            ],
            options={
                'ordering': ('-month',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('calculated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cap_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserve_draw', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('excess_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='organization.department')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.revenueperiod')),
            ],
            options={
                'ordering': ('department__order', 'department__name'),
                'constraints': [models.UniqueConstraint(fields=('period', 'department'), name='unique_department_per_period')],
            },
        ),
    ]
