# Generated by Django 5.2.15 on 2026-06-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='MooreSkillUp', max_length=120)),
                ('signatory_name', models.CharField(default='MooreSkillUp Team', max_length=120)),
                ('signatory_title', models.CharField(default='Director of Learning', max_length=120)),
                ('accent_color', models.CharField(default='#4f46e5', max_length=20)),
                ('signature_text', models.CharField(default='MooreSkillUp', max_length=120)),
                ('seal_text', models.CharField(default='MooreSkillUp · Verified', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate template',
                'verbose_name_plural': 'Certificate template',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
