# Generated by Django 5.2.15 on 2026-06-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
