# Generated by Django 5.2.15 on 2026-06-23 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='student', max_length=20)),
                ('selected_interest', models.CharField(blank=True, max_length=100)),
                ('selected_track', models.CharField(blank=True, max_length=100)),
                ('selected_tracks', models.JSONField(blank=True, default=list)),
                ('plan', models.CharField(default='free', max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
