# Generated by Django 5.2.15 on 2026-07-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='daily_goal_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
