# Generated by Django 5.2.15 on 2026-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_real_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
