# Generated by Django 5.2.17 on 2026-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pending_registration_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='founding_member_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='heard_about_us',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='heard_about_us_detail',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
