# Generated by Django 5.2.17 on 2026-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_studentprofile_founding_member_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='heard_about_us',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='heard_about_us_detail',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
