# Generated by Django 5.2.17 on 2026-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_backfill_referral_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
