# Generated by Django 5.2.15 on 2026-06-17 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_admin_role'),
        ('courses', '0006_courseversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden')], default='published', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('course', 'student')},
            },
        ),
    ]
