# Generated by Django 5.2.15 on 2026-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_is_recommended_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='pending_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
