# Generated by Django 5.2.15 on 2026-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_deletion_reason_course_pending_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='scheme_of_work',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
