# Generated by Django 5.2.15 on 2026-07-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_allow_blank_course_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='course-banners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_image_alt',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_theme',
            field=models.CharField(blank=True, default='default', max_length=40),
        ),
    ]
