# Generated by Django 5.2.15 on 2026-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='progression_mode',
            field=models.CharField(choices=[('open', 'Open'), ('sequential', 'Section by section')], default='open', max_length=20),
        ),
    ]
