# Generated by Django 5.2.17 on 2026-09-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_decline_reason_course_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
