# Generated by Django 5.2.17 on 2026-09-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_optional_section_and_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mux_playback_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
