# Generated by Django 5.2.15 on 2026-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack')], max_length=20),
        ),
    ]
