# Generated by Django 5.2.17 on 2026-09-15 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def record_existing_modes(apps, schema_editor):
    """Say what the payments taken before this field were.

    A simulated checkout carries `simulated=1` in its authorization URL. Every
    other payment so far went through a Paystack *test* key: no live key had
    been configured on any environment when this field arrived, so none of it
    was money. Left at the "live" default, test checkouts would stay in revenue.
    """
    Payment = apps.get_model("payments", "Payment")
    Transaction = apps.get_model("payments", "Transaction")
    simulated = Transaction.objects.filter(authorization_url__contains="simulated=1").values("payment_id")
    Payment.objects.filter(id__in=simulated).update(mode="simulated")
    Payment.objects.exclude(id__in=simulated).update(mode="test")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('test', 'Paystack test mode'), ('simulated', 'Simulated')], default='live', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(record_existing_modes, migrations.RunPython.noop),
    ]
