# Generated by Django 5.2.17 on 2026-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_list_price_discountcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processor_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
